title: Hallison Oliveira
description: >- 
  Blog de desenvolvimento de software
baseurl: ""
url: "https://hallisonoliveira.com.br"
timezone: America/Sao_Paulo

markdown: kramdown
permalink: /:title/
# paginate: 3
# paginate_path: /page:num/

pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

google_analytics: "G-11GCXLC7Y0"

# o18y
languages: ["pt", "en"]
default_lang: "pt"

exclude_from_localizations: ["javascript", "images", "css"]
