title: Hallison Oliveira
description: >- # this means to ignore newlines until "baseurl:"
  Blog de desenvolvimento de software
url: "http://hallisonoliveira.gitghub.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "devblog" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

